config/routes.rb
WolfHowl::Application.routes.draw do

  resource :sessions, :only => [:new, :create, :destroy]

  resources :users#, :only => [:new, :create, :show, :edit, :update]

  namespace :circle do
    resources :groups do
      member do
        put 'set_admin/:user_id', :action => :set_admin
        put 'canel_admin/:user_id', :action => :canel_admin
      end
      resources :group_users, :only => [:create] 

      resources :budgets
      resources :accounts
      resources :activities do 
        resources :activity_users, :only => [:create]
        resources :budgets
        resources :accounts
      end    
    end
  end

  namespace :personal do
    resources :users, :only =>[:edit,:update] do
      resources :budgets
      resources :accounts do
        get 'statistics', :on => :collection
      end
      resources :activities do 
        resources :budgets
        resources :accounts
      end
    end
  end

  namespace :admin do
    

    resources :categories

    resource :sessions

    root :to => "home#index"
  end

  root :to => 'home#index'

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/circle/accounts_controller.rb
class Circle::AccountsController < Circle::ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    # @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
    # @activities = @current_user.activities
    # @account = Account.new

    
    @account = Account.new
    @group = Group.find(params[:group_id]) if params.has_key?(:group_id)
    @budgets = @group.budgets
    @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
    @activities = @group.activities
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
      @group = Group.find(params[:group_id]) if params.has_key?(:group_id)
      @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
      @account = @current_user.create_account(params[:account], @activity, @group)
    respond_to do |format|
      if @account.valid?
        format.html { redirect_to circle_group_path(@group), notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/circle/activities_controller.rb
class Circle::ActivitiesController < Circle::ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @group = Group.find(params[:group_id])
    @activity = Activity.new
    @group_id = params[:group_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @group = Group.find(params[:group_id])
    @activity =  @group.create_activity(params[:activity].merge!({:user_id => @current_user.id}))
    @current_user.join_activity(@activity, nil, true) if @activity.valid?
    if @activity.valid?
      return render 'circle/groups/index'
    else
      return render action: 'new'
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/circle/activity_users_controller.rb
class Circle::ActivityUsersController < Circle::ApplicationController
  # GET /activity_users
  # GET /activity_users.json
  def index
    @activity_users = ActivityUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activity_users }
    end
  end

  # GET /activity_users/1
  # GET /activity_users/1.json
  def show
    @activity_user = ActivityUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity_user }
    end
  end

  # GET /activity_users/new
  # GET /activity_users/new.json
  def new
    @activity_user = ActivityUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity_user }
    end
  end

  # GET /activity_users/1/edit
  def edit
    @activity_user = ActivityUser.find(params[:id])
  end

  # POST /activity_users
  # POST /activity_users.json
  def create
    # group = Group.find(:group_id)
    activity = Activity.find(params[:activity_id])
    @activity_user = @current_user.join_activity(activity)
    # @activity_user = ActivityUser.new(params[:activity_user])

    respond_to do |format|
      if @activity_user.valid?
        format.html { redirect_to circle_group_path(activity.owner), notice: 'Activity user was successfully created.' }
        format.json { render json: @activity_user, status: :created, location: @activity_user }
      else
        format.html { render action: "new" }
        format.json { render json: @activity_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activity_users/1
  # PUT /activity_users/1.json
  def update
    @activity_user = ActivityUser.find(params[:id])

    respond_to do |format|
      if @activity_user.update_attributes(params[:activity_user])
        format.html { redirect_to @activity_user, notice: 'Activity user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_users/1
  # DELETE /activity_users/1.json
  def destroy
    @activity_user = ActivityUser.find(params[:id])
    @activity_user.destroy

    respond_to do |format|
      format.html { redirect_to activity_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/circle/application_controller.rb
class Circle::ApplicationController < ApplicationController
  # layout 'circle'
  layout 'personal'
end

app/controllers/circle/budgets_controller.rb
class Circle::BudgetsController < Circle::ApplicationController
  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @budgets }
    end
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    @budget = Budget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @budget }
    end
  end

  # GET /budgets/new
  # GET /budgets/new.json
  def new
    @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
    @group = Group.find(params[:group_id]) if params.has_key?(:group_id)
    @budget = Budget.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @budget }
    end
  end

  # GET /budgets/1/edit
  def edit
    @budget = Budget.find(params[:id])
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @group = Group.find(params[:group_id]) if params.has_key?(:group_id)
    @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
    @budget = @group.create_budget(params[:budget], @current_user, @activity)

    respond_to do |format|
      if @budget.valid?
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render json: @budget, status: :created, location: @budget }
      else
        format.html { render action: "new" }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /budgets/1
  # PUT /budgets/1.json
  def update
    @budget = Budget.find(params[:id])

    respond_to do |format|
      if @budget.update_attributes(params[:budget])
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget = Budget.find(params[:id])
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/circle/categories_controller.rb
class Circle::CategoriesController < Circle::ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/circle/group_users_controller.rb
class Circle::GroupUsersController < Circle::ApplicationController
  before_filter :current_group
  # GET /group_users
  # GET /group_users.json
  def index
    @group_users = GroupUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @group_users }
    end
  end

  # GET /group_users/1
  # GET /group_users/1.json
  def show
    @group_user = GroupUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group_user }
    end
  end

  # GET /group_users/new
  # GET /group_users/new.json
  def new
    @group = Group.new
    # @group_user = @current_user.join_group(@group)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group_user }
    end
  end

  # GET /group_users/1/edit
  def edit
    @group_user = GroupUser.find(params[:id])
  end

  # POST /group_users
  # POST /group_users.json
  def create
    # @group_user = GroupUser.new(params[:group_user])
    @group_user = @current_user.join_group(@group)
    respond_to do |format|
      if @group_user
        format.html { redirect_to [:circle, @group], notice: 'Group user was successfully created.' }
        format.json { render json: @group_user, status: :created, location: @group_user }
      else
        format.html { render action: "new" }
        format.json { render json: @group_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /group_users/1
  # PUT /group_users/1.json
  def update
    @group_user = GroupUser.find(params[:id])

    respond_to do |format|
      if @group_user.update_attributes(params[:group_user])
        format.html { redirect_to @group_user, notice: 'Group user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_users/1
  # DELETE /group_users/1.json
  def destroy
    @current_user.quit_group(@group)
    respond_to do |format|
      format.html { redirect_to groups_path }
      format.json { head :no_content }
    end
  end


  private
  def current_group
    @group = Group.find(params[:group_id])
    @group_user = GroupUser.find(params[:id]) if params.has_key?(:id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/circle/groups/_form.html.erb
<%= form_for([:circle,@group]) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "圈子名" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "圈子介绍" %><br />
    <%= f.text_area :description, :rows => 4 %>
  </div>

  <div class="actions">
    <%= f.submit "保存" %>
  </div>
<% end %>

app/views/circle/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/circle/groups/index.html.erb
<%= content_for :operation_bar do %>
  <div class="container">
    <ul class="bs-docs-social-buttons">
      <li>
        <%= link_to '创建我的圈子', new_circle_group_path %>
      </li>
      <% if @current_user.is_create_group?(@group) %>
        <li>
          <%= link_to '编辑这个圈子', edit_circle_group_path(@group) %> 
        </li>
        <li>
          <%= link_to "删除这个圈子？", [:circle,@group], :method => :delete, data: { confirm: '你确定删除这个圈子么？' } %>
        </li>
      <% else %>
            <% if @current_user.joined_group?(@group) %>
              <%= link_to '退出这个圈子!', "/groups/#{@group.id}/group_users/#{@current_user.joined_group(@group).id}", :method => :delete, data: { confirm: '你确定退出这个圈子么？' } %>
            <% else %>
              <%= link_to '喜欢？加入这个圈子!', circle_group_group_users_path(@group), :method => :post %>
            <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
        <div class="pagination pagination-small">
          <ul>
            <li>
              <%= link_to_unless( @group.first?, '上一个', circle_groups_path(:index => 'prev',:current_group_id => @group.id )) %>
            </li>
            <li>
              <%= link_to_unless( @group.last?, '下一个',circle_groups_path(:index => 'next',:current_group_id => @group.id)) %>
            </li>
          </ul>
        </div>
  </div>
  <div class="row">
    <p>
    <%= @group.name %> / <%= link_to @group.user.nick_name, user_path(@group.user) %> <br/>
    圈子等级:<%= @group.level %>  成员数:<%= @group.member_count %>   粉丝数:<%= @group.following_count %>
    </p>

    <div class="span8">
      <div class="row">
        <div class="span4">
          <p>
            <%= @group.description %>
          </p>

              <ul id="group_tab" class="nav nav-tabs">
                <li><a href="#activities_<%= @group.id %>" data-toggle="tab">活动</a></li>
                <li><a href="#budgets_<%= @group.id %>" data-toggle="tab">预算</a></li>
                <li><a href="#accounts_<%= @group.id %>" data-toggle="tab">帐务</a></li>
              </ul>

              <div class="tab-content">
                <div class="tab-pane active" id="activities_<%= @group.id %>">
                  <% if @group.activities.empty? %>
                    <%= link_to "没有活动，发起一个让大家来参与吧！", new_circle_group_activity_path(@group) %>
                  <% else %>
                    <% @group.activities.each do |active| %>
                      <div>
                        <%= active.subject %> / <%= link_to active.user.nick_name, user_path(active.user) %> / <%= active.start_date.strftime("%Y-%m-%d") %> -- <%= active.end_date.strftime("%Y-%m-%d") %>
                        <br />

                        总预算：<%= active.total_budgets_sum %> / 目前支出：<%= active.total_accounts_sum %> / 当前余额：<%= active.balance_sum %> 
                        <br />
                        我应该支出：<%= active.personal_outcome_account(@current_user) %>
                        <br />
                        我已经支出：<%= active.personal_outcome_total_account(@current_user) %> 
                        <br />
                        我还应该支付：<%= active.personal_outcome_should_account(@current_user)%>

                        <br />

                        <%= link_to( "创建预算", new_circle_group_activity_budget_path(@group,active)) if @current_user.is_admin_group?(@group) %>
                        <%= link_to(" / 添加帐务",new_circle_group_activity_account_path(@group,active)) if @current_user.is_admin_group?(@group) %>
                        <%= link_to(" / 参见活动",circle_group_activity_activity_users_path(@group,active), :method => :post) if (!@current_user.joind_activity?(active) && !@current_user.is_create_group?(@group)) %>
                        <%= link_to(" / 退出活动",circle_group_activity_activity_users_path(@group,active), :method => :delete, data: { confirm: '你确定退出该活动么？' }) if (@current_user.joind_activity?(active) && !@current_user.is_create_group?(@group)) %>
                      </div>
                    <% end %>
                    <% if @current_user.is_admin_group?(@group) %>
                      <%= link_to "发起活动", new_circle_group_activity_path(@group) %>
                    <% end %>
                  <% end %>
                </div>
                <div class="tab-pane" id="budgets_<%= @group.id %>">
                  <% if @group.budgets.empty? %>
                    <%= link_to "还没有预算的，策划一个新预算！", new_circle_group_budget_path(@group) %>
                  <% else %>
                    <% @group.budgets.each do |budget| %>
                        <%= "#{budget.total_sum}  #{budget.created_at.strftime('%Y-%m-%d %H:%M:%S')}  #{budget.description}" %>  <br/>
                    <% end %>
                    <% if @current_user.is_admin_group?(@group) %>
                      <%= link_to "策划一个新预算！", new_circle_group_budget_path(@group) %>
                    <% end %>
                  <% end %>
                </div>
                <div class="tab-pane" id="accounts_<%= @group.id %>">
                  <% if @group.accounts.empty? %>
                  <%= link_to "做好帐哦，来记一个吧！", new_circle_group_account_path(@group) %>
                  <% else %>
                    <% @group.accounts.each do |account| %>
                        <%= "#{account.sum}  #{account.created_at.strftime('%Y-%m-%d %H:%M:%S')}  #{account.remark}" %>  <br/>
                    <% end %>
                    <% if @current_user.is_admin_group?(@group) %>
                      <%= link_to "记个账先！", new_circle_group_account_path(@group) %>
                    <% end %>
                  <% end %>
                </div>
              </div>

        </div>
        <div class="span3">
          <% unless @current_user.is_create_group?(@group) %> 
            <% if @current_user.joined_group?(@group) %>
              <%= link_to '退出这个圈子!', "/groups/#{@group.id}/group_users/#{@current_user.joined_group(@group).id}", :method => :delete, data: { confirm: '你确定退出这个圈子么？' } %>
            <% else %>
              <%= link_to '喜欢？加入这个圈子!', circle_group_group_users_path(@group), :method => :post %>
            <% end %>
          <% else %>
              <%= link_to '编辑我的圈子', edit_circle_group_path(@group) %> / <%= link_to "删除这个圈子？", [:circle,@group], :method => :delete, data: { confirm: '你确定删除这个圈子么？' } %>
          <% end %>
          <br/>
          该小组的成员
          <ul class="unstyled">
            <% @group.users.each do |member| %>
              <li>
                <%= link_to member.nick_name, user_path(member) %>
                <% if member.is_admin_group?(@group) %>
                  / 管理员
                  <% if @current_user.is_create_group?(@group) %>
                  <%= link_to(" / 取消管理员", "/groups/#{@group.id}/canel_admin/#{member.id}", :method => :put) unless @current_user.is_create_group?(@group)%>
                  <% end %>
                <% elsif @current_user.is_create_group?(@group) %>
                  / <%= link_to "设为管理员", "/groups/#{@group.id}/set_admin/#{member.id}", :method => :put %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#group_tab').tab('show');
  })
</script>

app/views/circle/groups/new.html.erb
<h1>创建我的圈子</h1>

<%= render 'form' %>

<%= link_to '返回圈子', circle_groups_path %>

app/views/circle/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Description:</b>
  <%= @group.description %>
</p>

<p>
  <b>Level:</b>
  <%= @group.level %>
</p>

<p>
  <b>Status:</b>
  <%= @group.status %>
</p>

<p>
  <b>Following count:</b>
  <%= @group.following_count %>
</p>

<p>
  <b>Member count:</b>
  <%= @group.member_count %>
</p>

<p>
  <b>User:</b>
  <%= @group.user_id %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>