config/routes.rb
WolfHowl::Application.routes.draw do

  resource :sessions, :only => [:new, :create, :destroy]

  resources :users#, :only => [:new, :create, :show, :edit, :update]

  namespace :circle do
    resources :groups do
      member do
        put 'set_admin/:user_id', :action => :set_admin
        put 'canel_admin/:user_id', :action => :canel_admin
      end
      resources :group_users, :only => [:create] 

      resources :budgets
      resources :accounts
      resources :activities do 
        resources :activity_users, :only => [:create]
        resources :budgets
        resources :accounts
      end    
    end
  end

  namespace :personal do
    resources :users, :only =>[:edit,:update] do
      resources :budgets
      resources :accounts do
        get 'statistics', :on => :collection
      end
      resources :activities do 
        resources :budgets
        resources :accounts
      end
    end
  end

  namespace :admin do
    

    resources :categories

    resource :sessions

    root :to => "home#index"
  end

  root :to => 'home#index'

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/circle/accounts_controller.rb
class Circle::AccountsController < Circle::ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    # @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
    # @activities = @current_user.activities
    # @account = Account.new

    
    @account = Account.new
    @group = Group.find(params[:group_id]) if params.has_key?(:group_id)
    @budgets = @group.budgets
    @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
    @activities = @group.activities
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
      @group = Group.find(params[:group_id]) if params.has_key?(:group_id)
      @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
      @account = @current_user.create_account(params[:account], @activity, @group)
    respond_to do |format|
      if @account.valid?
        format.html { redirect_to circle_group_path(@group), notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/personal/accounts_controller.rb
#encoding: utf-8
class Personal::AccountsController < Personal::ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    if params[:top_menu_type] == 'io_type'
      @top_menu_type = 'io_type'
      unless params[:io_type] == 'in_come'
        @accounts = @current_user.accounts.outcome.page(params[:page])
        @io_type = 'out_come'
      else
        @accounts = @current_user.accounts.income.page(params[:page])
        @io_type = 'in_come'
      end
    elsif params[:top_menu_type] == 'category_type'
      @top_menu_type = 'category_type'
      if params.has_key?(:category_id)
        category = Category.find(params[:category_id].to_i)
      else
        category = Category.top_categories.first
      end
      @category_id = category.id
      @accounts = @current_user.accounts.where(:genre_type => 'Category', :genre_id => category.id).page(params[:page])
    elsif params[:top_menu_type] == 'activity_type'
      @top_menu_type = 'activity_type'
      if params.has_key?(:activity_id)
        activity = Activity.find(params[:activity_id].to_i)
      else
        activity = @current_user.activities.first
      end
      @activity_id = activity.id
      @accounts = @current_user.accounts.where(:genre_type => 'Activity', :genre_id => activity.id).page(params[:page])
    elsif params[:top_menu_type] == 'budget_type'
      @top_menu_type = 'budget_type'
      if params.has_key?(:budget_id)
        budget = Budget.find(params[:budget_id].to_i)
      else
        budget = @current_user.budgets.first
      end
      @budget_id = budget.id
      @accounts = @current_user.accounts.where(:genre_type => 'Budget', :genre_id => budget.id).page(params[:page])
    else
      @top_menu_type = 'all'
      @accounts = @current_user.accounts.page(params[:page])
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
    # return render :show
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
    @budgets = @current_user.budgets
    @activities = @current_user.activities
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    # @account = Account.new(params[:account])
    if params.has_key?(:activity_id)
      @activity = Activity.find(params[:activity_id]) if params.has_key?(:activity_id)
      @account = @current_user.create_account(params[:account], @activity)
      if @account.valid?
        return redirect_to personal_user_activity_path(@current_user,@activity)
      else
        return render :new
      end
    else
      @account = @current_user.create_account(params[:account])
      if @account.valid?
        return redirect_to personal_user_accounts_path(@current_user)
      else

      end
    end
    # respond_to do |format|
    #   if @account.valid?
    #     format.html { redirect_to @account, notice: 'Account was successfully created.' }
    #     format.json { render json: @account, status: :created, location: @account }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @account.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  def statistics
      @top_menu_type = 'statistics'
    if params.has_key?(:statistics_type)
      @paint_chart = true
      start_date = params[:start_date].to_date
      end_date = params[:end_date].to_date
      if params[:statistics_type] == 'in_out_type'
        @h = LazyHighCharts::HighChart.new('graph') do |f|
          f.options[:chart][:defaultSeriesType] = "area"
          f.series(:name=>'收入', :data=> Account.statistics(@current_user,:io_type,Account::STATISTICS[:io_type][:io_income],start_date,end_date))
          f.series(:name=>'支出', :data=> Account.statistics(@current_user,:io_type,Account::STATISTICS[:io_type][:io_outcome],start_date,end_date))
        end
      elsif params[:statistics_type] == 'category_type'
        @h = LazyHighCharts::HighChart.new('graph') do |f|
          f.options[:chart][:defaultSeriesType] = "area"
          Category.top_categories.each do |category|
            f.series(:name=>category.name, :data=>Account.statistics(@current_user, :category_type, category.id, start_date, end_date))
          end
        end        
      elsif params[:statistics_type] == 'activity_type'
      elsif params[:statistics_type] == 'activity_type'
      elsif params[:statistics_type] == 'budget_type'
      end
    end
  end
end

app/controllers/personal/activities_controller.rb
class Personal::ActivitiesController < Personal::ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = @current_user.activities.order('id desc').page(params[:page])
    @activity = @activities.first
    @activity.check_update_status if @activity.present?
    return render :show
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activities = @current_user.activities.order('id desc').page(params[:page])
    @activity = Activity.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new({:start_date => Time.now, :end_date => Time.now})
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = @current_user.activities.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = @current_user.create_activity(params[:activity])

    respond_to do |format|
      if @activity.errors.empty?
        format.html { redirect_to personal_user_activities_path(@current_user), notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to personal_user_activities_url(@current_user), notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to personal_user_activities_url(@current_user) }
      format.json { head :no_content }
    end
  end

end

app/controllers/personal/application_controller.rb
class Personal::ApplicationController < ApplicationController
  layout 'personal'

  before_filter :redirect_guest_view

  private

  def redirect_guest_view
  	unless is_login?
  		Rails.logger.info("======Guest,con:#{params}")
  		return render "#{params[:controller]}/guest/#{params[:action]}"
  	end
  end

end

app/helpers/accounts_helper.rb
#encoding: utf-8
module AccountsHelper
	def io_type_option(account)
		"<option value='#{Account::IO_TYPE_INCOME}'>收入</option><option value='#{Account::IO_TYPE_OUTCOME}'>支出</option>"
	end

	def statistics_type_help
		"<option value='in_out_type'>收支类别</option><option value='category_type'>帐务类别</option><option value='activity_type'>活动类别</option><option value='budget_type'>预算类别</option>"
	end

	def paid_user_option(group,activity)
		options = ''
		if activity.present?
			activity.users.each do |user|
				options += "<option value='#{user.id}'>#{user.nick_name}</option>"
			end
		else
			group.users.each do |user|
				options += "<option value='#{user.id}'>#{user.nick_name}</option>"
			end
		end
		return options
	end
end

app/views/personal/accounts/_form.html.erb
<%= form_for([:personal, @current_user, @activity, @account]) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sum, "金额" %><br />
    <%= f.number_field :sum %>
  </div>
  <% unless @activity.present? %>
    <div class="field">
      <%= f.label :io_type, "收支类型" %><br />
      <%= select_tag "account[io_type]", io_type_option(@account).html_safe %>
    </div>
    <div class="field">
        <ul id="genre_tab" class="nav nav-tabs">
          <li class="active"><a href="#category_type" val="Category" data-toggle="tab">类别帐务</a></li>
          <li><a href="#budget_type" val="Budget" data-toggle="tab">预算帐务</a></li>
          <li><a href="#activity_type" val="Activity" data-toggle="tab">活动帐务</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="category_type">
            <%= select_tag('account[genre_id]', option_groups_from_collection_for_select(Category.top_categories, :children, :name, :id, :name, 3)) %>
          </div>
          <div class="tab-pane" id="budget_type">
            <%= select_tag('account[genre_id]', options_from_collection_for_select(@budgets, :id, :name)) %>
          </div>   
          <div class="tab-pane" id="activity_type">
            <%= select_tag('account[genre_id]', options_from_collection_for_select(@activities, :id, :subject)) %>
          </div>             
        </div>
        <%= f.hidden_field(:genre_type, :value => 'Category') %>
    </div>    
  <% else %>
      <%= f.hidden_field(:io_type,:vaule => Account::IO_TYPE_OUTCOME) %>
  <% end %>



  <div class="field">
    <%= f.label :remark, "备注" %><br />
    <%= f.text_area :remark, :cols => 15, :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit "记起" %>
  </div>
<% end %>
<script type="text/javascript">
  $(document).ready(function(){
    $('#genre_type').tab('show');
    $('a[data-toggle="tab"]').on('shown', function (e) {
      $('#account_genre_type').attr('value',$(e.target).attr('val'))
    });
  })
</script>

app/views/personal/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/personal/accounts/index.html.erb
<%= content_for :operation_bar do %>
  <div class="container">
    <ul class="bs-docs-social-buttons">
      <li>
        <%= link_to '新建帐务', new_personal_user_account_path(@current_user) %>
      </li>

      <li class="follow-btn">
        
      </li>
      <li class="tweet-btn">
       
      </li>
    </ul>
  </div>
<% end %>

<h1>我的帐务</h1>
    <div class="row-fluid">
        <div class="span2">
            <ul class="nav nav-pills nav-stacked">
                <li class="<%= @top_menu_type == 'all' ? 'active' : '' %>">
                    <%= link_to "所有帐务", personal_user_accounts_path(@current_user) %>
                </li>
                <li class="<%= @top_menu_type == 'io_type' ? 'active' : '' %>">
                    <%= link_to "收支类型", personal_user_accounts_path(@current_user, :top_menu_type => 'io_type') %>
                </li> 
                <li class="<%= @top_menu_type == 'category_type' ? 'active' : '' %>">
                    <%= link_to "帐务类别", personal_user_accounts_path(@current_user, :top_menu_type => 'category_type') %>
                </li> 
                <li class="<%= @top_menu_type == 'activity_type' ? 'active' : '' %>">
                    <%= link_to "活动帐务", personal_user_accounts_path(@current_user, :top_menu_type => 'activity_type') %>
                </li>
                <li class="<%= @top_menu_type == 'budget_type' ? 'active' : '' %>">
                    <%= link_to "预算帐务", personal_user_accounts_path(@current_user, :top_menu_type => 'budget_type') %>
                </li> 
                <li class="<%= @top_menu_type == 'statistics' ? 'active' : '' %>">
                    <%= link_to "帐务统计", statistics_personal_user_accounts_path(@current_user, :top_menu_type => 'budget_type') %>
                </li>                                                                              
            </ul>
        </div>
        <div class="span8">
            <div>
                <% if @top_menu_type == 'io_type' %>
                    <ul class="nav nav-tabs">
                      <li class="<%= @io_type == 'out_come' ? 'active' : '' %>">
                        <%= link_to "支出", personal_user_accounts_path(@current_user, :top_menu_type => 'io_type', :io_type => 'out_come') %>
                      </li>
                      <li class="<%= @io_type == 'in_come' ? 'active' : '' %>">
                        <%= link_to "收入", personal_user_accounts_path(@current_user, :top_menu_type => 'io_type', :io_type => 'in_come') %>
                      </li>
                    </ul>
                <% elsif @top_menu_type == 'category_type' %>
                    <ul class="nav nav-tabs">
                      <% Category.top_categories.each do |category| %>
                        <li class="<%= @category_id == category.id ? 'active' : '' %>">
                          <%= link_to category.name, personal_user_accounts_path(@current_user, :top_menu_type => 'category_type', :category_id => category.id) %>
                        </li>
                      <% end %>
                    </ul>
                <% elsif @top_menu_type =='activity_type' %>
                    <ul class="nav nav-tabs">
                      <% @current_user.activities.each do |activity| %>
                        <li class="<%= @activity_id == activity.id ? 'active' : '' %>">
                          <%= link_to activity.subject, personal_user_accounts_path(@current_user, :top_menu_type => 'activity_type', :activity_id => activity.id) %>
                        </li>
                      <% end %>
                    </ul>       
                <% elsif @top_menu_type =='budget_type' %>
                    <ul class="nav nav-tabs">
                      <% @current_user.budgets.each do |budget| %>
                        <li class="<%= @budget_id == budget.id ? 'active' : '' %>">
                          <%= link_to budget.name, personal_user_accounts_path(@current_user, :top_menu_type => 'budget_type', :budget_id => budget.id) %>
                        </li>
                      <% end %>
                    </ul>                                                    
                <% end %>
            </div>
            <table class="table table-striped">
              <tr>
                <th>金额</th>
                <th>收支类型</th>
                <th>所属类型</th>
                <th>备注</th>
                <th>记帐时间</th>
                <th>操作</th>
                <th></th>
              </tr>

            <% @accounts.each do |account| %>
              <tr>
                <td><%= account.sum %></td>
                <td><%= Account::IO_TYPE[account.io_type] %></td>
                <td><%= account.genre_type_detail %></td>
                <td><%= account.remark %></td>
                <td><%= account.created_at.strftime("%Y-%m-%d") %></td>
                <td><%= link_to '详情', personal_user_account_path(@current_user, account) %></td>
                <td><%= link_to '编辑', edit_personal_user_account_path(@current_user, account) %></td>
                <td><%= link_to '删除', [:personal, @current_user, account], method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
            </table>
            <div>
                <%= paginate @accounts %>
            </div>
        </div>
    </div>

<br />

app/views/personal/accounts/new.html.erb
<h1>记一笔账</h1>

<%= render 'form' %>

app/views/personal/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sum:</b>
  <%= @account.sum %>
</p>

<p>
  <b>Io type:</b>
  <%= @account.io_type %>
</p>

<p>
  <b>Owner type:</b>
  <%= @account.owner_type %>
</p>

<p>
  <b>Owner:</b>
  <%= @account.owner_id %>
</p>

<p>
  <b>Budget type:</b>
  <%= @account.budget_type %>
</p>

<p>
  <b>Budget:</b>
  <%= @account.budget_id %>
</p>

<p>
  <b>Remark:</b>
  <%= @account.remark %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/personal/accounts/statistics.html.erb
<h2>帐务统计</h2>
<div>
	<%= form_tag(statistics_personal_user_accounts_path(@current_user),:method => :get) do %>
		<div class="field">
			<%= label_tag '统计类别' %>
			<%= select_tag 'statistics_type',statistics_type_help.html_safe %>
		</div>
	  	<div class="field">
	    	<%= label_tag "开始时间" %><br />
	    	<%= text_field_tag :start_date %>
	  	</div>
	  	<div class="field">
		    <%= label_tag "结束时间" %><br />
		    <%= text_field_tag :end_date %>
	  	</div>			
			<%= submit_tag '统计' %>
	<% end %>
</div>
<div>
	<% if @paint_chart %>
		<%= high_chart("my_id", @h) %>
	<% end %>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#start_date').datepicker({ 'format' : 'yyyy-mm-dd'});
    $('#end_date').datepicker({ 'format' : 'yyyy-mm-dd'});
  })
</script>