config/routes.rb
WolfHowl::Application.routes.draw do

  resource :sessions, :only => [:new, :create, :destroy]

  resources :users#, :only => [:new, :create, :show, :edit, :update]

  namespace :circle do
    resources :groups do
      member do
        put 'set_admin/:user_id', :action => :set_admin
        put 'canel_admin/:user_id', :action => :canel_admin
      end
      resources :group_users, :only => [:create] 

      resources :budgets
      resources :accounts
      resources :activities do 
        resources :activity_users, :only => [:create]
        resources :budgets
        resources :accounts
      end    
    end
  end

  namespace :personal do
    resources :users, :only =>[:edit,:update] do
      resources :budgets
      resources :accounts do
        get 'statistics', :on => :collection
      end
      resources :activities do 
        resources :budgets
        resources :accounts
      end
    end
  end

  namespace :admin do
    

    resources :categories

    resource :sessions

    root :to => "home#index"
  end

  root :to => 'home#index'

end

app/models/category.rb
#encoding: utf-8
class Category < ActiveRecord::Base
  # paginates_per 5

  attr_accessible :description, :level, :name, :postion, :status, :user_id, :parent_id, :io_type
  belongs_to :user
  belongs_to :parent, :class_name => :Category, :foreign_key => :parent_id
  has_many :children, :class_name => :Category, :foreign_key => :parent_id
  validates :name, :presence => { :message => "不能为空！"}
  LEVEL_TOP = 0
  IO_TYPE_INCOME = 0
  IO_TYPE_OUTCOME = 1
  IO_TYPE = {IO_TYPE_INCOME => '收入', IO_TYPE_OUTCOME => '支出'}
  # LEVEL_ROOT = 0
  scope :top_categories, where(:level => LEVEL_TOP) 
  scope :income, where(:io_type => IO_TYPE_INCOME)
  scope :outcome, where(:io_type => IO_TYPE_OUTCOME)  
  # scope :root_categories, where(:level => LEVEL_ROOT)   


  def create_child(user,params)
  	params.delete(:parent_id)
  	category = self.children.build(params.merge!({:user_id => user.id}))
  	category.level = self.level + 1
  	self.max_postion = self.children.size + 1
  	self.save
  	return category
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @io_type = Category::IO_TYPE_INCOME
    @io_type = Category::IO_TYPE_OUTCOME if params[:io_type].to_i == Category::IO_TYPE_OUTCOME

    if params.has_key?(:top_category_id)
      @parent = Category.find(params[:top_category_id])
      @io_type = @parent.io_type
    end

    if @io_type == Category::IO_TYPE_OUTCOME
      @top_categories = Category.outcome.top_categories
    else
      @top_categories = Category.income.top_categories
    end
    @parent = @top_categories.first if @parent.nil?
    # parent = Category.income.top_categories.first if @io_type == Category::IO_TYPE_INCOME
    # parent = Category.outcome.top_categories.first if @io_type == Category::IO_TYPE_INCOME
    # parent = Category.income.top_categories.first if parent.nil?

    # @top_categories = parent.children

    @categories = @parent.children if @parent.present?
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    @top_categories = Category.top_categories
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    @top_categories = Category.top_categories
  end

  # POST /categories
  # POST /categories.json
  def create
    if params[:category][:parent_id].present?
      parent = Category.find(params[:category][:parent_id])
      @category = parent.create_child(@current_user,params[:category])
    else
      @category = Category.create(params[:category].merge!({:user_id => @current_user.id}))
    end
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/circle/categories_controller.rb
class Circle::CategoriesController < Circle::ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/personal/categories_controller.rb
class Personal::CategoriesController < Personal::ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "类别名" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :io_type, "收支类型" %><br />
    <%= select_tag('category[io_type]', "<option value='0'>收入</option><option value='1'>支出</option>".html_safe ) %>
  </div>  
  <div class="field">
    <%= f.label "类别描述" %><br />
    <%= f.text_area :description, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label "类别位置" %><br />
    <%= f.number_field :postion %>
  </div>
  <div class="field">
    <%= f.label "父类别" %><br />
    <%= select_tag('category[parent_id]', options_from_collection_for_select(@top_categories, "id", "name"),:prompt => "顶级类别") %>
  </div>
  <div class="actions">
    <%= f.submit "保存" %>
  </div>
<% end %>

app/views/admin/categories/index.html.erb
<div class="row-fluid sortable">        
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-user"></i> 所有类别</h2>
            <div class="box-icon">
                <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
            </div>
        </div>
        <ul class="nav nav-pills">
            <ul class="nav nav-pills">
              <li class="<%= 'active' if @io_type == 0 %>">
                <%= link_to '收入', admin_categories_path(:io_type => Category::IO_TYPE_INCOME) %>
              </li>
              <li class="<%= 'active' if @io_type == 1 %>">
                <%= link_to '支出', admin_categories_path(:io_type => Category::IO_TYPE_OUTCOME) %>
              </li>
            </ul>
          <% @top_categories.each do |category| %>
          <li class="<%= 'active' if @parent == category %>">
            <%= link_to category.name, admin_categories_path(:top_category_id => category.id) %>
          </li>
          <% end %>
        </ul>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
              <thead>
                  <tr>
                      <th>类别名</th>
                      <th>类别描述</th>
                      <th>类别级数</th>
                      <th>父类别</th>
                      <th>类别状态</th>
                      <th>类别位置</th>
                      <th>创建者</th>
                      <th>操作</th>
                  </tr>
              </thead>   
              <tbody>
                <% @categories.each do |category| %>
                <tr>
                <td><%= category.name %></td>
                <td><%= category.description %></td>
                <td><%= category.level %></td>
                <td><%= category.parent.name if category.parent.present? %></td>
                <td><%= category.status %></td>
                <td><%= category.postion %></td>
                <td><%= category.user.nick_name %></td>
                <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
                <td><%= link_to 'Destroy', [:admin,category], method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
                <% end %>
              </tbody>
          </table>            
        </div>
<%= link_to '新增类别', new_admin_category_path %>
    </div><!--/span-->
</div><!--/row-->

app/views/admin/categories/new.html.erb
<h1>新增类别</h1>

<%= render 'form' %>

<%= link_to '返回列表', admin_categories_path %>